### ISSUE TITLE
warning: supporting new formats is a breaking change!

### ISSUE THREAD

**Issue by onkoe** [mindeng/nom-exif#11]
You need to add the `#[non_exhaustive]` attribute to the following types. Otherwise, changing them is a violation of semantic versioning and will break dependant crates:

- `nom_exif::error::Error`
- `nom_exif::exif::tags::ExifTag`
- `nom_exif::file::FileFormat`

In other words, it's a breaking change to support new formats, make new errors, or add to the recognized EXIF tag list! See: https://rust-lang.github.io/rust-clippy/rust-1.81.0/index.html#/exhaustive_enums

To prevent this after the next major version, please consider adding the following to Cargo.toml:

```toml
# other stuff...

[lints.clippy]
"exhaustive_enums" = "deny" # all `pub enum`s are `#[non_exhaustive]` 
```
